In [4]:
# from phoenix_qiskit.basics import *
from canopus import CanonicalGate
from qiskit.quantum_info import Operator, Clifford, SparsePauliOp
from qiskit.circuit.library import *
from phoenix_qiskit.hamiltonian import Hamiltonian
from qiskit import QuantumCircuit

In [ ]:
qc = QuantumCircuit(3)
qc.append(CNOTEquivCliffordGate('X', 'Y'), [1, 2])
instr = qc.to_instruction()

qc2 = QuantumCircuit(4)
qc2.append(instr, [1,2,3])
qc2.decompose().draw()

q_0: ────────
             
q_1: ────────
     ┌──────┐
q_2: ┤0     ├
     │  Cxy │
q_3: ┤1     ├
     └──────┘

In [ ]:
type(instr)

qiskit.circuit.instruction.Instruction

In [ ]:
qc.data[0].operation

Instruction(name='cxy', num_qubits=2, num_clbits=0, params=[])

In [ ]:
from qiskit.circuit import Instruction
isinstance(CanonicalGate(1,2,3), )

True

In [57]:
Clifford(qc).to_circuit().draw()

q_0: ───────────────────────────
     ┌───┐┌───┐     ┌─────┐┌───┐
q_1: ┤ H ├┤ S ├──■──┤ Sdg ├┤ H ├
     ├───┤├───┤┌─┴─┐├─────┤├───┤
q_2: ┤ H ├┤ S ├┤ X ├┤ Sdg ├┤ H ├
     └───┘└───┘└───┘└─────┘└───┘

In [61]:
sp.paulis.x

array([[ True,  True],
       [ True, False]])

In [65]:
ham = Hamiltonian(['XX', 'YY'])
local_ham, nonlocal_ham = ham.separate_local_nonlocal()

In [70]:
# local_ham.paulis.x

import numpy as np

In [72]:
local_ham.with_ops

array([[False, False]])

In [39]:
import numpy as np
weights = np.sum(ham.with_ops, axis=1)
local_mask = weights <= 1
nonlocal_mask = ~local_mask

In [43]:
Hamiltonian(ham.paulis[local_mask], ham.coeffs[local_mask])

SparsePauliOp(['II'],
              coeffs=[0.+0.j])

In [44]:
ham.paulis[local_mask].num_qubits

2

In [21]:
sp = SparsePauliOp(['IX', 'YY'], coeffs=[1.0, 2.0])
sp

SparsePauliOp(['IX', 'YY'],
              coeffs=[1.+0.j, 2.+0.j])

In [22]:
print(sp.paulis.evolve(CXGate(), frame='s'))

sp.paulis = sp.paulis.evolve(CXGate(), frame='s')

['XX', '-ZX']


In [32]:
SparsePauliOp([], [])

QiskitError: 'Input Pauli list is empty.'

In [25]:
sp.coeffs

array([ 1.+0.j, -2.+0.j])

In [29]:
isinstance(CNOTEquivCliffordGate('X', 'z'), CNOTEquivCliffordGate | fSwapEquivCliffordGate)

True

In [31]:
SparsePauliOp(['XX', 'YY'])

SparsePauliOp(['XX', 'YY'],
              coeffs=[1.+0.j, 1.+0.j])

In [2]:
Clifford(fSwapGate()).to_labels()

['+XY', '+YX', '-YI', '-IY']

In [11]:
fSwapEquivCliffordGate('Z', 'X').definition.draw(fold=-1)

┌────────┐     
q_0: ─────┤0       ├─────
     ┌───┐│  Fswap │┌───┐
q_1: ┤ H ├┤1       ├┤ H ├
     └───┘└────────┘└───┘

In [10]:
CNOTEquivCliffordGate('Y', 'X').definition.draw(fold=-1)

┌─────┐┌───┐     ┌───┐┌───┐
q_0: ┤ Sdg ├┤ H ├──■──┤ H ├┤ S ├
     └─────┘└───┘┌─┴─┐└───┘└───┘
q_1: ────────────┤ X ├──────────
                 └───┘

In [5]:
CNOTEquivCliffordGate('Z', 'X').to_matrix()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [6]:
Operator(CNOTEquivCliffordGate('Z', 'X').definition).to_matrix()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [10]:
Operator(iSwapEquivClifford('Z', 'Z').inverse().definition)


Operator([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
          [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]],
         input_dims=(2, 2), output_dims=(2, 2))


In [14]:
import numpy as np

np.kron(SdgGate().to_matrix(), SdgGate().to_matrix()) @ iSwapEquivClifford('Z', 'Z').to_matrix()

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [18]:
iSwapEquivClifford('Z', 'Z').to_matrix() @ np.kron(SGate().to_matrix(), SGate().to_matrix())

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])