In [1]:
import numpy as np
from itertools import combinations
from phoenix.models import BSF
from copy import copy
from phoenix import Circuit
import rustworkx as rx
from phoenix.utils.arch import gene_random_circuit
from phoenix.synthesis import grouping
from phoenix.utils import passes
import json
import qiskit
from phoenix.utils import arch
from phoenix.utils.passes import obtain_front_layer, obtain_last_layer, front_full_width_circuit, last_full_width_circuit
from phoenix.utils.passes import obtain_front_layer_from_circuit, obtain_last_layer_from_circuit


verify `obtain_front_layer_from_circuit` and `obtain_front_layer` and `obtain_front_layer(front_full_width_circuit())`

In [2]:
for _ in range(100):
    circ = arch.gene_random_circuit(10, 100)
    l1 = obtain_front_layer(circ)
    l2 = obtain_front_layer_from_circuit(circ)
    assert l1 == l2

    l1 = obtain_front_layer(front_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1))
    l2 = obtain_front_layer_from_circuit(circ, predicate=lambda g: g.num_qregs > 1)
    assert l1 == l2

for _ in range(100):
    circ = arch.gene_random_circuit(10, 100).nonlocal_structure
    l1 = obtain_front_layer(circ)
    l2 = obtain_front_layer_from_circuit(circ)
    assert l1 == l2

    l1 = obtain_front_layer(front_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1))
    l2 = obtain_front_layer_from_circuit(circ, predicate=lambda g: g.num_qregs > 1)
    assert l1 == l2

verify `obtain_last_layer_from_circuit` and `obtain_last_layer` and `obtain_last_layer(last_full_width_circuit())`

In [5]:
for _ in range(100):
    circ = arch.gene_random_circuit(10, 100)
    l1 = obtain_last_layer(circ)
    l2 = obtain_last_layer_from_circuit(circ)
    assert l1 == l2

    l1 = obtain_last_layer(last_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1))
    l2 = obtain_last_layer_from_circuit(circ, predicate=lambda g: g.num_qregs > 1)
    assert l1 == l2

for _ in range(100):
    circ = arch.gene_random_circuit(10, 100).nonlocal_structure
    l1 = obtain_last_layer(circ)
    l2 = obtain_last_layer_from_circuit(circ)
    assert l1 == l2

    l1 = obtain_last_layer(last_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1))
    l2 = obtain_last_layer_from_circuit(circ, predicate=lambda g: g.num_qregs > 1)
    assert l1 == l2

In [7]:
dag = circ.to_dag()

In [ ]:
isinstance(10, )

False

In [23]:
l1

[Z{6←7}, Z{8←3}, H{2←5}]

In [24]:
c = Circuit(l1)
c

Circuit(num_gates: 3, num_qubits: 6)

In [25]:
c.remove(c[0])

In [28]:
set.union([1,2], [2,3])

TypeError: descriptor 'union' for 'set' objects doesn't apply to a 'list' object

verify `obtain_front_layer` and `last_full_width_circuit`

In [2]:
# circ = arch.gene_random_circuit(10, 100)
# dag = circ.to_dag()
for _ in range(100):
    circ = arch.gene_random_circuit(10, 100)
    f = obtain_front_layer(last_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1, reverse=True))
    l = obtain_last_layer(last_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1, reverse=False))
    assert set(f)==set(l)

In [4]:
f = obtain_front_layer(last_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1, reverse=True))
l = obtain_last_layer(last_full_width_circuit(circ, predicate=lambda g: g.num_qregs > 1, reverse=False))

In [5]:
f

[Z{8←1}, Y{7←2}, H{0←5}]

In [7]:
l

[H{0←5}, Y{7←2}, Z{8←1}]

In [80]:
f = passes.obtain_front_layer(circ)
f

[SDG{7}, H{0}, Z{4←1}, Z{6←2}, Y{9←8}, H{3←5}]

In [81]:
passes.obtain_front_layer(Circuit(list(reversed(circ))))

[X{0←2}, RX(0.35π){4}, X{7}, H{5←6}, H{3←9}, H{1←8}]

In [76]:
Circuit(list(reversed(circ)))

Circuit(num_gates: 694, num_qubits: 10)

In [ ]:
from functools import reduce
from operator import add,

In [48]:
mapping = {1:2, 2:1, 3:3}
front_layer = [[1,2], [2,3]]
front_logic_qregs = np.array([g for g in front_layer])
front_phys_qregs = np.vectorize(mapping.get)(front_logic_qregs) 
# extending_logic_qregs = np.array([g.qregs for g in extending_layer])
# extending_phys_qregs = np.vectorize(mapping.get)(extending_logic_qregs)

In [69]:
if reversed(circ.gates): print(10)

10


In [54]:
np.where(front_phys_qregs[[0,0,0], [1,1,1]] == 1)

(array([0, 1, 2]),)

In [47]:
import time
import numpy as np

# 创建数据
data_size = 10000000
ls = [float(i) for i in range(data_size)]

# 测试 set(ls) 的速度
start_time = time.time()
unique_set = set(ls)
print(f"set(ls) 计算时间: {time.time() - start_time:.6f} 秒")

# 测试 np.unique(ls) 的速度
start_time = time.time()
unique_np = np.unique(ls)
print(f"np.unique(ls) 计算时间: {time.time() - start_time:.6f} 秒")

set(ls) 计算时间: 0.163342 秒
np.unique(ls) 计算时间: 0.320954 秒


In [15]:
from qiskit.transpiler.passes import SabreLayout

In [26]:
mapping = {i:i for i in range(300)}
device = arch.gene_grid_2d_graph(300)
for _ in range(1000):
    arch.is_executable(gates.RXX(0.1).on(np.random.choice(300, 2, replace=False).tolist()), mapping, device=device)

In [7]:
import sys
def get_platform_parallel_default():
    """
    Returns the default parallelism flag value for the current platform.

    Returns:
        parallel_default: The default parallelism flag value for the
        current platform.

    """
    # Default False on Windows
    if sys.platform == "win32":
        parallel_default = False
    # On macOS default false on Python >=3.8
    elif sys.platform == "darwin":
        parallel_default = False
    # On linux (and other OSes) default to True
    else:
        parallel_default = True

    return parallel_default

import multiprocessing

In [8]:
from qiskit.utils import local_hardware_info

In [10]:
import os

In [13]:
os.cpu_count()

14

In [44]:
with open('./benchmarks/uccsd_json/CH2_cmplt_BK_sto3g.json', 'r') as file:
    uccsd_json = json.load(file)

In [46]:
grouping.group_paulis_and_coeffs(uccsd_json['paulis'], uccsd_json['coeffs'])

{(0,
  1,
  3,
  4,
  5,
  6,
  7,
  9,
  10,
  11): (['YXIXXYZYIZZXII',
   'XXIXYYZYIZZXII',
   'YXIXZYZYIZZXII',
   'ZXIXYYZYIZZXII'], array([ 0.0125, -0.0125,  0.0125, -0.0125])),
 (1,
  2,
  3,
  4,
  5,
  8,
  9,
  11,
  12,
  13): (['IZYYXXIIYXIYYX',
   'IZYYYXIIYXIYXX',
   'IZYYYXIIXXIYYX',
   'IZYYXXIIXXIYXX',
   'IZXYYXIIYXIYYX',
   'IZXYXXIIYXIYXX',
   'IZXYXXIIXXIYYX',
   'IZXYYXIIXXIYXX',
   'IZYYYXIIYXIYZX',
   'IZYYXXIIXXIYZX',
   'IZXYXXIIYXIYZX',
   'IZXYYXIIXXIYZX',
   'IZYYYXIIZXIYYX',
   'IZYYXXIIZXIYXX',
   'IZXYXXIIZXIYYX',
   'IZXYYXIIZXIYXX',
   'IZYYXXIIZXIYZX',
   'IZXYYXIIZXIYZX',
   'IZYYZXIIYXIYYX',
   'IZYYZXIIXXIYXX',
   'IZXYZXIIYXIYXX',
   'IZXYZXIIXXIYYX',
   'IZYYZXIIXXIYZX',
   'IZXYZXIIYXIYZX',
   'IZYYZXIIZXIYXX',
   'IZXYZXIIZXIYYX',
   'IZYYZXIIZXIYZX',
   'IZZYYXIIYXIYYX',
   'IZZYXXIIYXIYXX',
   'IZZYXXIIXXIYYX',
   'IZZYYXIIXXIYXX',
   'IZZYXXIIYXIYZX',
   'IZZYYXIIXXIYZX',
   'IZZYXXIIZXIYYX',
   'IZZYYXIIZXIYXX',
   'IZZYYXIIZXIYZX',
   'IZZY

In [32]:
circ = gene_random_circuit(12, 500)

In [35]:
c1 = rebase.rebase_to_canonical(circ)

In [36]:
c2 = rebase.rebase_to_canonical_by_bqskit(circ)


In [38]:
c1.num_nonlocal_gates, c2.num_nonlocal_gates

(1729, 1305)

In [ ]:
c1.depth_nonlocal, c2.depth_nonlocal

(464, 399)

In [23]:
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

s1 = Student("Alice", 20)
s2 = Student("Bob", 21)

In [24]:
g = rx.PyGraph()
g.add_node(s1)
g.add_node(s2)

1

In [30]:
for node in g.nodes():
    print(node.name)

Alice
Bob


In [29]:
g[0]

In [17]:
circ = Circuit()
circ.append(gates.RX(0.1).on(0))
circ.append(gates.RX(0.1).on(1))


In [20]:
set([g for g in circ.gates])

{RX(0.03π){0}, RX(0.03π){1}}

In [8]:
tab = BSF(['XXZ', 'XXY', 'IIX'])
tab.which_local_paulis, tab.which_nonlocal_paulis

(array([2]), array([0, 1]))

In [9]:
popped = copy(tab)

In [10]:
popped.mat, popped.coeffs, popped.signs = popped.mat[tab.which_local_paulis], popped.coeffs[tab.which_local_paulis], popped.signs[tab.which_local_paulis]


In [12]:
popped

BSF(size=[1, 3], num_nonlocals=0, total_weight=1)

In [13]:
tab

BSF(size=[3, 3], num_nonlocals=2, total_weight=3)

In [28]:
tab.mat, tab.coeffs, tab.signs = tab.mat[tab.which_nonlocal_paulis], tab.coeffs[tab.which_nonlocal_paulis], tab.signs[tab.which_nonlocal_paulis]

In [30]:
tab.which_local_paulis, tab.which_nonlocal_paulis

(array([2]), array([0, 1]))

In [31]:
tab.mat

array([[1, 1, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 1]])

In [12]:
a = np.arange(12).reshape(3, 4)
b = a.copy()


In [13]:
b[0] = np.zeros(4)
b

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
s = ['a', 'b']
n = [1, 2, 3]
[(si, ni) for si in s for ni in n]

[('a', 1), ('a', 2), ('a', 3), ('b', 1), ('b', 2), ('b', 3)]

In [17]:
b[0,0] = a[0,1]

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b

10

In [25]:
b = 10

In [25]:
np.array([Student('Alice', 20), Student('Bob', 22)])

array([<__main__.Student object at 0x10a2a4710>,
       <__main__.Student object at 0x10a2a6420>], dtype=object)

In [6]:
np.linalg.norm(a, ord=1, axis=1)

array([ 6., 22., 38.])

In [9]:
if np.array([10]):
    print('empty array is True')

empty array is True


In [11]:
np.array([10]).size

1