In [8]:
from tetris.utils.hardware import load_coupling_map, load_sycamore_graph, load_graph
import numpy as np

In [17]:
from qiskit import QuantumCircuit

In [24]:
import sys
sys.path.append('../')


from phoenix import Circuit, gates

In [27]:
Circuit([gates.H.on(0), gates.X.on(2)]).to_qiskit().draw()

┌───┐
q_0: ┤ H ├
     └───┘
q_1: ─────
     ┌───┐
q_2: ┤ X ├
     └───┘

In [50]:
qc1 = QuantumCircuit(4)
qc1.h(0)
qc1.cx(0, 1)

In [51]:
qc2 = QuantumCircuit(3)
qc2.cz(1, 2)
qc2.x(1)

In [52]:
qc2.qubits

[Qubit(QuantumRegister(3, 'q'), 0),
 Qubit(QuantumRegister(3, 'q'), 1),
 Qubit(QuantumRegister(3, 'q'), 2)]

In [62]:
qc1.draw()

┌───┐                                     
q_0: ┤ H ├──■──────────────────────────────────
     └───┘┌─┴─┐   ┌───┐   ┌───┐   ┌───┐   ┌───┐
q_1: ─────┤ X ├─■─┤ X ├─■─┤ X ├─■─┤ X ├─■─┤ X ├
          └───┘ │ └───┘ │ └───┘ │ └───┘ │ └───┘
q_2: ───────────■───────■───────■───────■──────
                                               
q_3: ──────────────────────────────────────────

In [59]:
qc1.compose(qc2, inplace=True)

In [60]:
qc1.compose(qc2, inplace=True).draw()

AttributeError: 'NoneType' object has no attribute 'draw'

In [29]:
circ1 = QuantumCircuit(3)
circ1.h([0, 1, 2])

circ2 = QuantumCircuit(3)
circ2.x([0, 1, 2])

circ = QuantumCircuit(6)
circ.compose(circ1, [0, 1, 2], inplace=True)
circ.compose(circ2, [3, 4, 5], inplace=True)

In [31]:
circ.draw()

┌───┐
q_0: ┤ H ├
     ├───┤
q_1: ┤ H ├
     ├───┤
q_2: ┤ H ├
     ├───┤
q_3: ┤ X ├
     ├───┤
q_4: ┤ X ├
     ├───┤
q_5: ┤ X ├
     └───┘

In [2]:
G, C = load_graph('manhattan')

In [10]:
np.unique(C)

array([0.e+00, 1.e+00, 1.e+06])

In [16]:
(C[0])

array([0.e+00, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+00, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06])

In [14]:
G[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
G, C = load_sycamore_graph(False)

In [7]:
C

array([[      0., 1000000., 1000000., ..., 1000000., 1000000., 1000000.],
       [1000000.,       0., 1000000., ..., 1000000., 1000000., 1000000.],
       [1000000., 1000000.,       0., ..., 1000000., 1000000., 1000000.],
       ...,
       [1000000., 1000000., 1000000., ...,       0., 1000000., 1000000.],
       [1000000., 1000000., 1000000., ..., 1000000.,       0., 1000000.],
       [1000000., 1000000., 1000000., ..., 1000000., 1000000.,       0.]])