In [8]:
from tetris.utils.hardware import load_coupling_map, load_sycamore_graph, load_graph
import numpy as np

In [2]:
G, C = load_graph('manhattan')

In [10]:
np.unique(C)

array([0.e+00, 1.e+00, 1.e+06])

In [16]:
(C[0])

array([0.e+00, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+00, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06,
       1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06, 1.e+06])

In [14]:
G[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
G, C = load_sycamore_graph(False)

In [7]:
C

array([[      0., 1000000., 1000000., ..., 1000000., 1000000., 1000000.],
       [1000000.,       0., 1000000., ..., 1000000., 1000000., 1000000.],
       [1000000., 1000000.,       0., ..., 1000000., 1000000., 1000000.],
       ...,
       [1000000., 1000000., 1000000., ...,       0., 1000000., 1000000.],
       [1000000., 1000000., 1000000., ..., 1000000.,       0., 1000000.],
       [1000000., 1000000., 1000000., ..., 1000000., 1000000.,       0.]])